name: Mool
options:
  bundleIdPrefix: com.mool
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: YES
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

targets:
  Mool:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Mool
        excludes:
          - "Resources/Assets.xcassets"
    resources:
      - path: Mool/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mool.app
        PRODUCT_NAME: Mool
        SWIFT_VERSION: "6.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_FILE: Mool/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Mool/Resources/Mool.entitlements
        ENABLE_HARDENED_RUNTIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: Mool/Resources/Mool.entitlements
    info:
      path: Mool/Resources/Info.plist
      properties:
        CFBundleName: Mool
        CFBundleDisplayName: Mool
        CFBundleIdentifier: com.mool.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "0.1.0"
        LSMinimumSystemVersion: "14.0"
        LSApplicationCategoryType: public.app-category.productivity
        NSPrincipalClass: NSApplication
        NSSupportsAutomaticTermination: false
        NSSupportsSuddenTermination: false
        LSUIElement: false
        NSCameraUsageDescription: "Mool needs camera access to record your webcam."
        NSMicrophoneUsageDescription: "Mool needs microphone access to record audio."
        NSScreenCaptureUsageDescription: "Mool needs screen recording permission to capture your screen."
        NSAppleEventsUsageDescription: "Mool uses Apple Events to support automation."
        CFBundleURLTypes: []
        NSHumanReadableCopyright: "© 2024 Mool. All rights reserved."
